all: libut flatner.o

CFLAGS = -I libut/include
LDFLAGS= -L libut -lut

CFLAGS += -g

flatner.o: flatner.c flatner.h
	$(CC) -c $(CFLAGS) $< $(LDFLAGS)

.PHONY: libut clean

libut:
	$(MAKE) -C libut -f Makefile.standalone

clean:
	rm -rf *.o
	$(MAKE) -C libut -f Makefile.standalone clean
